services:

  web:
    # image: a0939902239/magic-stream-web-prod:1.0.0
    image: a0939902239/magic-stream-web-prod:${IMAGE_TAG:-latest}
    container_name: magic-stream-web-prod
    ports:
    - "8081:80"
    restart: always
  
  api:
    #image: a0939902239/magic-stream-api-prod:1.0.0
    image: a0939902239/magic-stream-api-prod:${IMAGE_TAG:-latest}
    container_name: magic-stream-api-prod
    ports:
    - "8000:8000"


  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - movies:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
  seed:
    image: mongo:latest
    container_name: seed_mongo
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./seed:/seed-data
    command: >
      mongosh mongodb://db:27017/magic-stream-movies /seed-data/seed.js
    restart: "no"     # runs once, does not restart after completion


volumes:
  movies:
